### PR TITLE
Update base image

### PR DESCRIPTION
**Pull request by hazim1093**

### CODE REVIEW

**Comment by stakater-user** [comment]
@hazim1093 Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/Stakater%20Docker/job/builder-maven/job/PR-5/1/) has Failed!

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/builder-maven:3.5.4-jdk1.8-v1.16.8-SNAPSHOT-PR-5-2`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/builder-maven:3.5.4-jdk1.8-v1.16.8-SNAPSHOT-PR-5-3`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/builder-maven:3.5.4-jdk1.8-v1.16.8-SNAPSHOT-PR-5-4`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/builder-maven:3.5.4-jdk1.8-v1.16.8-SNAPSHOT-PR-5-5`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/builder-maven:3.5.4-jdk1.8-v1.16.8-SNAPSHOT-PR-5-7`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/builder-maven:3.5.4-jdk1.8-v2.0.1-SNAPSHOT-PR-5-8`

**Review by rasheedamir — APPROVED** [review]
Looks good

**Pull request merged**
